//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OcdlogisticsEntities : DbContext
    {
        public OcdlogisticsEntities()
            : base("name=OcdlogisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<PointOfContractPerson> PointOfContractPerson { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AboutUs> tbl_AboutUs { get; set; }
        public virtual DbSet<tbl_Address> tbl_Address { get; set; }
        public virtual DbSet<tbl_Brand> tbl_Brand { get; set; }
        public virtual DbSet<tbl_Business> tbl_Business { get; set; }
        public virtual DbSet<tbl_BusinessInfo> tbl_BusinessInfo { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Color> tbl_Color { get; set; }
        public virtual DbSet<Tbl_ContactUs> Tbl_ContactUs { get; set; }
        public virtual DbSet<tbl_ContectUsPage> tbl_ContectUsPage { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_Customers> tbl_Customers { get; set; }
        public virtual DbSet<tbl_CustomerShippingDetail> tbl_CustomerShippingDetail { get; set; }
        public virtual DbSet<tbl_CustomerType> tbl_CustomerType { get; set; }
        public virtual DbSet<tbl_Distribution_Packages> tbl_Distribution_Packages { get; set; }
        public virtual DbSet<tbl_Distribution_Packages_Info> tbl_Distribution_Packages_Info { get; set; }
        public virtual DbSet<tbl_DistributionServices> tbl_DistributionServices { get; set; }
        public virtual DbSet<tbl_Duration> tbl_Duration { get; set; }
        public virtual DbSet<Tbl_EducationBanner> Tbl_EducationBanner { get; set; }
        public virtual DbSet<tbl_FAQ> tbl_FAQ { get; set; }
        public virtual DbSet<tbl_FAQ_Questions> tbl_FAQ_Questions { get; set; }
        public virtual DbSet<tbl_File> tbl_File { get; set; }
        public virtual DbSet<Tbl_FindF> Tbl_FindF { get; set; }
        public virtual DbSet<tbl_Home_Page_Feature_Benifites> tbl_Home_Page_Feature_Benifites { get; set; }
        public virtual DbSet<tbl_HomePage_Packages> tbl_HomePage_Packages { get; set; }
        public virtual DbSet<tbl_Industry> tbl_Industry { get; set; }
        public virtual DbSet<tbl_Ingredient_Info> tbl_Ingredient_Info { get; set; }
        public virtual DbSet<tbl_Ingredients> tbl_Ingredients { get; set; }
        public virtual DbSet<Tbl_LearningPreference> Tbl_LearningPreference { get; set; }
        public virtual DbSet<tbl_Membership> tbl_Membership { get; set; }
        public virtual DbSet<Tbl_Misson> Tbl_Misson { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<Tbl_OurSolution> Tbl_OurSolution { get; set; }
        public virtual DbSet<tbl_OurTeamPage> tbl_OurTeamPage { get; set; }
        public virtual DbSet<tbl_PartnerCms> tbl_PartnerCms { get; set; }
        public virtual DbSet<tbl_Payments> tbl_Payments { get; set; }
        public virtual DbSet<tbl_PaymentsTypes> tbl_PaymentsTypes { get; set; }
        public virtual DbSet<Tbl_PrivacyPolicy> Tbl_PrivacyPolicy { get; set; }
        public virtual DbSet<tbl_Product> tbl_Product { get; set; }
        public virtual DbSet<tbl_Product_File> tbl_Product_File { get; set; }
        public virtual DbSet<tbl_Product_Line> tbl_Product_Line { get; set; }
        public virtual DbSet<tbl_ProductCategory> tbl_ProductCategory { get; set; }
        public virtual DbSet<tbl_ProductLoyalityCalculationType> tbl_ProductLoyalityCalculationType { get; set; }
        public virtual DbSet<tbl_ProductLoyalityRewards> tbl_ProductLoyalityRewards { get; set; }
        public virtual DbSet<tbl_ProductLoyalityRule> tbl_ProductLoyalityRule { get; set; }
        public virtual DbSet<tbl_ProductType> tbl_ProductType { get; set; }
        public virtual DbSet<tbl_ProductVendorsInfo> tbl_ProductVendorsInfo { get; set; }
        public virtual DbSet<tbl_ProfilePage> tbl_ProfilePage { get; set; }
        public virtual DbSet<tbl_Province> tbl_Province { get; set; }
        public virtual DbSet<tbl_Rceiver_ShippingDetail> tbl_Rceiver_ShippingDetail { get; set; }
        public virtual DbSet<Tbl_RefundPolicy> Tbl_RefundPolicy { get; set; }
        public virtual DbSet<tbl_Resources> tbl_Resources { get; set; }
        public virtual DbSet<tbl_ResourcesShedule> tbl_ResourcesShedule { get; set; }
        public virtual DbSet<tbl_ResourcesSpecialHour> tbl_ResourcesSpecialHour { get; set; }
        public virtual DbSet<tbl_ResourcesType> tbl_ResourcesType { get; set; }
        public virtual DbSet<tbl_Slider> tbl_Slider { get; set; }
        public virtual DbSet<tbl_SocailInfo> tbl_SocailInfo { get; set; }
        public virtual DbSet<tbl_Socails> tbl_Socails { get; set; }
        public virtual DbSet<tbl_SocialHandler> tbl_SocialHandler { get; set; }
        public virtual DbSet<Tbl_Sponser> Tbl_Sponser { get; set; }
        public virtual DbSet<Tbl_SponserEducation> Tbl_SponserEducation { get; set; }
        public virtual DbSet<tbl_SubscribeToNewsLatter> tbl_SubscribeToNewsLatter { get; set; }
        public virtual DbSet<tbl_TeamProfiles> tbl_TeamProfiles { get; set; }
        public virtual DbSet<tbl_UnitOfWeight> tbl_UnitOfWeight { get; set; }
        public virtual DbSet<tbl_UserSettings> tbl_UserSettings { get; set; }
        public virtual DbSet<tbl_Vendor_Product> tbl_Vendor_Product { get; set; }
        public virtual DbSet<tbl_Vendors> tbl_Vendors { get; set; }
        public virtual DbSet<tbl_WeekDay> tbl_WeekDay { get; set; }
        public virtual DbSet<Tbl_WhyChoose> Tbl_WhyChoose { get; set; }
        public virtual DbSet<tblIngredients> tblIngredients { get; set; }
        public virtual DbSet<tblProduct_line_Info> tblProduct_line_Info { get; set; }
        public virtual DbSet<tblRights> tblRights { get; set; }
        public virtual DbSet<tblVendorType> tblVendorType { get; set; }
        public virtual DbSet<TermsConditions> TermsConditions { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
