//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resources
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ResourcessTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual tbl_ResourcesType tbl_ResourcesType { get; set; }
        public virtual tbl_ResourcesShedule tbl_ResourcesShedule { get; set; }
    }
}
