//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FindF
    {
        public int Id { get; set; }
        public string VedioPath { get; set; }
        public string ImgPath { get; set; }
        public string ButtonSideText { get; set; }
        public string BoxHeading { get; set; }
        public string BoxContent { get; set; }
        public string BoxButonText { get; set; }
        public string MapBelowText { get; set; }
        public string OCDTeamHeading { get; set; }
        public string OCDTeamContent { get; set; }
        public string PartnerHeading { get; set; }
        public string PartnerContent { get; set; }
    }
}
