//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Distribution_Packages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Distribution_Packages()
        {
            this.tbl_Distribution_Packages_Info = new HashSet<tbl_Distribution_Packages_Info>();
        }
    
        public string Id { get; set; }
        public string Cost { get; set; }
        public Nullable<int> DurationType { get; set; }
        public string Features { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Distribution_Packages_Info> tbl_Distribution_Packages_Info { get; set; }
        public virtual tbl_Duration tbl_Duration { get; set; }
    }
}
