//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SocialHandler
    {
        public string Instagram { get; set; }
        public string LinkedIn { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public string Pintrest { get; set; }
        public string Snapchat { get; set; }
        public string Twitter { get; set; }
        public string Phone { get; set; }
        public string TextMessage { get; set; }
        public string Email { get; set; }
        public string HeaderImage110 { get; set; }
        public string FooterImage80 { get; set; }
        public bool VisaBit { get; set; }
        public bool MasterCard { get; set; }
        public bool Discover { get; set; }
        public bool AmercianExpress { get; set; }
        public bool Paypal { get; set; }
        public bool SSl { get; set; }
        public bool Norten { get; set; }
        public string Adress { get; set; }
        public string BusinessName { get; set; }
        public string CompanyName { get; set; }
        public string CusinessSlogan { get; set; }
        public string LegalBusinessName { get; set; }
        public string PrimerColor { get; set; }
        public string PrimerColor2 { get; set; }
        public string PrimerColor3 { get; set; }
        public string SecondaryColor { get; set; }
        public string SecondaryColor2 { get; set; }
        public string SecondaryColor3 { get; set; }
        public string SecondaryColor4 { get; set; }
        public string SecondaryColor5 { get; set; }
        public string UserId { get; set; }
        public string Tiktok { get; set; }
        public string TitalBarFont { get; set; }
        public string TitalBarSize { get; set; }
        public string TitalBarColor { get; set; }
        public string HeaderFont { get; set; }
        public string HeaderColor { get; set; }
        public string HeaderSize { get; set; }
        public string BodyFont { get; set; }
        public string BodyColor { get; set; }
        public string BodySize { get; set; }
        public string SubHeaderFont { get; set; }
        public string SubHeaderColor { get; set; }
        public string SubHeaderSize { get; set; }
        public string BodyContentFont { get; set; }
        public string BodyContentColor { get; set; }
        public string BodyContentSize { get; set; }
        public string SloganFont { get; set; }
        public string SloganColor { get; set; }
        public string SloganSize { get; set; }
        public string QuoteFont { get; set; }
        public string QuoteSize { get; set; }
        public string QuoteColor { get; set; }
        public string WebsiteFont { get; set; }
        public string WebsiteColor { get; set; }
        public string WebsiteSize { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
