//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HomePage_Packages
    {
        public int Id { get; set; }
        public string Cost { get; set; }
        public Nullable<int> DurationType { get; set; }
        public string Name { get; set; }
        public string link { get; set; }
        public string Icon { get; set; }
    
        public virtual tbl_Duration tbl_Duration { get; set; }
    }
}
