//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResourcesSpecialHour
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<bool> IsClose { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
