//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResourcesShedule
    {
        public Nullable<int> WeekDayId { get; set; }
        public string Open { get; set; }
        public string Close { get; set; }
        public string UserId { get; set; }
        public string ResourceId { get; set; }
        public Nullable<bool> IsEmployeeAvailable { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_Resources tbl_Resources { get; set; }
        public virtual tbl_WeekDay tbl_WeekDay { get; set; }
    }
}
