//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductLoyalityRewards
    {
        public string ProductId { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> LoyalityCalculationTypeId { get; set; }
        public Nullable<int> LoyalityRuleId { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_ProductLoyalityCalculationType tbl_ProductLoyalityCalculationType { get; set; }
        public virtual tbl_ProductLoyalityRule tbl_ProductLoyalityRule { get; set; }
    }
}
