//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_Ingredient_Info = new HashSet<tbl_Ingredient_Info>();
            this.tbl_ProductVendorsInfo = new HashSet<tbl_ProductVendorsInfo>();
            this.tbl_Product_File = new HashSet<tbl_Product_File>();
            this.tbl_Vendor_Product = new HashSet<tbl_Vendor_Product>();
            this.tblProduct_line_Info = new HashSet<tblProduct_line_Info>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ProductAvailability { get; set; }
        public Nullable<bool> IsAvalaibleOnEeommerence { get; set; }
        public Nullable<long> CostPrice { get; set; }
        public Nullable<long> RetailPrice { get; set; }
        public Nullable<long> SalonPrice { get; set; }
        public string Variances { get; set; }
        public string Fragrance { get; set; }
        public string FeaturesAndBenifits { get; set; }
        public string FullDescription { get; set; }
        public string ShortDescription { get; set; }
        public bool IsInventoryTrackable { get; set; }
        public string UPC { get; set; }
        public string Part { get; set; }
        public string SKU { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string IngredientsId { get; set; }
        public string TypeId { get; set; }
        public string SubCategId { get; set; }
        public string ProductColorId { get; set; }
        public Nullable<int> ProductSizeWeightTypeId { get; set; }
        public string ProductWeight { get; set; }
        public string IndustryId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SupplyPrice { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public string SR_NO { get; set; }
    
        public virtual tbl_Color tbl_Color { get; set; }
        public virtual tbl_Industry tbl_Industry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ingredient_Info> tbl_Ingredient_Info { get; set; }
        public virtual tbl_ProductLoyalityRewards tbl_ProductLoyalityRewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProductVendorsInfo> tbl_ProductVendorsInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Product_File> tbl_Product_File { get; set; }
        public virtual tbl_ProductCategory tbl_ProductCategory { get; set; }
        public virtual tbl_ProductType tbl_ProductType { get; set; }
        public virtual tbl_UnitOfWeight tbl_UnitOfWeight { get; set; }
        public virtual tblIngredients tblIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Vendor_Product> tbl_Vendor_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct_line_Info> tblProduct_line_Info { get; set; }
    }
}
