//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EducationBanner
    {
        public int Id { get; set; }
        public string BannerHeading { get; set; }
        public string BannerContent { get; set; }
        public string BannerImg { get; set; }
        public string Img { get; set; }
        public string ImgHeading { get; set; }
        public string ImgContent { get; set; }
    }
}
