//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Misson
    {
        public int Id { get; set; }
        public string Heading { get; set; }
        public string Contents { get; set; }
        public string ImgUrl { get; set; }
        public string BelowHeading { get; set; }
        public string BlowContents { get; set; }
        public string VedioUrl { get; set; }
    }
}
