//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FAQ_Questions
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> FAQ_Id { get; set; }
    
        public virtual tbl_FAQ tbl_FAQ { get; set; }
        public virtual tbl_FAQ tbl_FAQ1 { get; set; }
        public virtual tbl_FAQ tbl_FAQ2 { get; set; }
    }
}
