//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product_File
    {
        public string Id { get; set; }
        public string ProductId { get; set; }
        public string FileId { get; set; }
    
        public virtual tbl_File tbl_File { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
