//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AboutUs
    {
        public int Id { get; set; }
        public string MainSliderImg { get; set; }
        public string SliderOverlayColor { get; set; }
        public string SliderOverlayHeading { get; set; }
        public string SliderOverlayContent { get; set; }
        public string MainSliderBelowHeading { get; set; }
        public string VideoHeading { get; set; }
        public string VideoPath { get; set; }
        public string VideoContent { get; set; }
        public string VideoContentFooter { get; set; }
        public string AttentionDetailHeading { get; set; }
        public string AttentionDetailContent { get; set; }
        public string AttentíonDetailFooter { get; set; }
        public string AttentíonDetailImgPath { get; set; }
        public string FirstFullScreenImgPath { get; set; }
        public string FirstFullScreenBelowHeading { get; set; }
        public string FirstFullScreenBelowContent { get; set; }
        public string FirstFullScreenBelowFooter { get; set; }
        public string FirstFullScreenBelowImgPath { get; set; }
        public string FirstFullScreenBelowSecondImgPath { get; set; }
        public string FirstFullScreenBelowSecondHeading { get; set; }
        public string FirstFullScreenBelowSecondContent { get; set; }
        public string FirstFullScreenBelowSecondFooter { get; set; }
        public string SecondFullScreenImgPath { get; set; }
        public string SecondFullScreenBelowHeading { get; set; }
        public string SecondFullScreenBelowContent { get; set; }
        public string SecondFullScreenbelowfooter { get; set; }
        public string SecondFullScreenbelowImgPath { get; set; }
        public string SecondFullScreenbelowSecondImgPath { get; set; }
        public string SecondFullScreenbelowSecondHeading { get; set; }
        public string SecondFullScreenbelowSecondContent { get; set; }
        public string SecondFullScreenbelowSecondFooter { get; set; }
        public string ThirdFullScreenImg { get; set; }
        public string ThirdFullScreenBelowImg { get; set; }
        public string ThirdFullScreenBelowFirstLayoverContent { get; set; }
        public string ThirdFullScreenBelowFirstLayoverColor { get; set; }
        public string FullScreenBelowSecondImg { get; set; }
        public string ThirdFullScreenBelowSecondLayoverContent { get; set; }
        public string ThirdFullScreenBelowSecondLayoverColor { get; set; }
        public string ThirdFullScreenBelowFooterText { get; set; }
    }
}
