//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OurTeamPage
    {
        public int OurTeamId { get; set; }
        public string OurTeamBackimg { get; set; }
        public string semenarimgtext { get; set; }
        public string ExpertImage { get; set; }
        public string SeminarImage { get; set; }
        public string OurTeamPageQuote { get; set; }
        public string Expertimgtext { get; set; }
        public string BannerImgHeading { get; set; }
        public string BannerImgText { get; set; }
        public string Bannerimg { get; set; }
        public string BannerImgColor { get; set; }
        public string ContentImgColor { get; set; }
        public string FootrImgColor { get; set; }
    }
}
