//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TeamProfiles
    {
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public string Speciality { get; set; }
        public string Position { get; set; }
        public string ShortDescription { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Tweeter { get; set; }
        public string Pintrestr { get; set; }
        public string Youtube { get; set; }
        public string LinkedIn { get; set; }
        public string Message { get; set; }
        public string TeamImage { get; set; }
        public string FavoriteQuote { get; set; }
        public string Bio { get; set; }
        public string Credentials { get; set; }
        public string Experience { get; set; }
        public string PassionandHobbies { get; set; }
        public string MyWork { get; set; }
        public Nullable<bool> IsOnDisplay { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
