//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContectUsPage
    {
        public int ContectUsPageID { get; set; }
        public string ContectUsPageBannerImage { get; set; }
        public string ContectUsPageBackgroundcolor { get; set; }
        public string ServicedeskEmail { get; set; }
        public string Emailus { get; set; }
        public string CarrerEmail { get; set; }
        public string PressEmail { get; set; }
        public string PatnershipEmail { get; set; }
    }
}
