//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OurSolution
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Img { get; set; }
        public string ImgText { get; set; }
        public string ButtonColor { get; set; }
        public string ButtonText { get; set; }
        public string ButtonUrl { get; set; }
    }
}
