//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserSettings
    {
        public string UserId { get; set; }
        public string ProfilePageBannermage { get; set; }
        public string BackGroungdColor { get; set; }
        public string ProfilePageExpertImage { get; set; }
        public string ProfilePageSeminarImage { get; set; }
        public string ProfilePageQuote { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
