//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProfilePage
    {
        public int ProfilePageId { get; set; }
        public string bckimg1 { get; set; }
        public string BackGroungdColorBanner { get; set; }
        public string ProfilePageExpertImage { get; set; }
        public string ProfilePageSeminarImage { get; set; }
        public string ProfilePageQuote { get; set; }
        public string bckimg2 { get; set; }
        public string bckimg3 { get; set; }
        public string ExpertImageText { get; set; }
        public string SeminarImageText { get; set; }
        public string BackGroungdColorbody { get; set; }
        public string BackGroungdColorFootr { get; set; }
    }
}
