//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Slider
    {
        public string SliderId { get; set; }
        public string UserId { get; set; }
        public string SliderImage { get; set; }
        public string SliderHeading { get; set; }
        public string SliderContent { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
