//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct_line_Info
    {
        public string ID { get; set; }
        public string ProductId { get; set; }
        public string BrandId { get; set; }
        public string ProductLineId { get; set; }
    
        public virtual tbl_Brand tbl_Brand { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_Product_Line tbl_Product_Line { get; set; }
    }
}
