//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcdlogisticsSolution.DomainModels.Models.Entity_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRights
    {
        public bool EventsList { get; set; }
        public bool CreateEvent { get; set; }
        public bool Delete { get; set; }
        public bool EditEvent { get; set; }
        public bool AllowToSeeUserList { get; set; }
        public bool AlllowToCreateUser { get; set; }
        public bool AllowToDeleteUser { get; set; }
        public bool AllowToUpdateUser { get; set; }
        public bool AllowToSeeEventTypeList { get; set; }
        public bool AlllowToCreateEventType { get; set; }
        public bool AllowToDeleteEventType { get; set; }
        public bool AllowToUpdateEventType { get; set; }
        public bool MailList { get; set; }
        public bool MailCreate { get; set; }
        public bool MembershipCreate { get; set; }
        public bool MembershipEdit { get; set; }
        public bool MembershipList { get; set; }
        public bool MembershipDelete { get; set; }
        public bool SocialHandlersEdit { get; set; }
        public bool TeamProfileCreate { get; set; }
        public bool TeamProfileEdit { get; set; }
        public bool TeamProfileList { get; set; }
        public string RoleId { get; set; }
        public bool TeamProfileDelete { get; set; }
        public bool AllowToCreateRolesAndRights { get; set; }
        public bool AllowToUpdateRolesAndRights { get; set; }
        public bool AllowToDeleteRolesAndRights { get; set; }
        public bool AllowToListRolesAndRights { get; set; }
        public bool AllowToUpdateGlobalSettings { get; set; }
        public bool AllowToUpdateSlider { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
